---
name: Math-Permute-List
version: 1.001
author:
  - 'PhilipRBrenan@handybackup.com'
abstract: Generate all the permutations of a list.
license: perl
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Math::Permute::List:
    file: lib/Math/Permute/List.pm
    version: 1.001
resources:
  license: http://dev.perl.org/licenses/
