---
name: Math-Permute-List
version: 1.0
author:
abstract: "Generate all permutations of a list.\n"
license: perl
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Math::Permute::List:
    file: lib/Math/Permute/List.pm
    version: 1.0
resources:
  license: http://dev.perl.org/licenses/
